# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!
target ‘testSheets’ do
    pod 'GoogleAPIClientForREST/Sheets', '~> 1.2.1'
    pod 'GoogleSignIn', '~> 4.1.1'
end

